services:
  frama-c:
    platform: linux/amd64
    image: framac/frama-c:30.0
    volumes:
      - ./frama-c:/home/opam/src

  # docker compose build
  # docker compose run stainless src/AVLTree.scala
  stainless:
    platform: linux/amd64
    build:
      dockerfile_inline: |
        FROM eclipse-temurin:8u442-b06-jre
        ARG STAINLESS_VERSION

        RUN apt-get update && apt-get install -y wget unzip libgomp1

        WORKDIR /app

        RUN echo "Fetching https://github.com/epfl-lara/stainless/releases/download/v$$STAINLESS_VERSION/stainless-dotty-standalone-$$STAINLESS_VERSION-linux.zip"
        RUN wget --quiet https://github.com/epfl-lara/stainless/releases/download/v$$STAINLESS_VERSION/stainless-dotty-standalone-$$STAINLESS_VERSION-linux.zip
        RUN echo "Unzipping stainless-dotty-standalone-$$STAINLESS_VERSION-linux.zip"
        RUN unzip stainless-dotty-standalone-$$STAINLESS_VERSION-linux.zip && rm -f stainless-dotty-standalone-$$STAINLESS_VERSION-linux.zip

        ENTRYPOINT ["/app/stainless"]
      args:
        STAINLESS_VERSION: 0.9.9.0
    volumes:
      - ./stainless:/app/src
